### ISSUE TITLE
Is there any way to make the corners rounded for applications in XFCE? Or is it possible to make all corners square?

### ISSUE THREAD

**Issue by pinbuck** [FabianOvrWrt/adw-xfwm4#1]
![image](https://github.com/FabianOvrWrt/adw-xfwm4/assets/96911866/85b4ea9c-799a-4202-94d2-910dc095ba25)
Settings menus for XFCE seem to only take the current GTK theme but not the WM theme...

**Comment by FabianOvrWrt** [comment]
It's a problem with your compositor it seems, try using picom if xfwm refuses to enable composition.

**Comment by pinbuck** [comment]
wayland fixes most of these issues so I closed. Maybe someday XFCE will be on track with wayland. In the current point, both kde and gnome handle theme scaling pretty well mostly due to wayland.
